# -*- coding: utf-8 -*-

# Main constants
TIMEOUT_INFO = 3000
TIMEOUT_ERROR = 6000
WORK_STR_SEPARATOR = ' - '

# Columns constants
COLUMN_DATE_FROM = 0
COLUMN_DATE_TO = 1
COLUMN_NAME = 2
COLUMN_STATE = 3
COLUMN_CITY = 4
COLUMN_HALL = 5
COLUMN_TYPE = 6
COLUMN_FESTIVAL = 7
COLUMN_WORKS = 8
COLUMN_SOLOISTS = 9
COLUMN_DIRIGENTS = 10
COLUMN_CHOIRS = 11
COLUMN_NOTE = 12
COLUMN_CONCERT_ID = 13
COLUMN_FESTIVAL_ID = 14

# End of constants.py