# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainform.ui'
#
# Created: Fri Nov 21 10:04:32 2014
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.frame_search = QtWidgets.QFrame(self.centralwidget)
        self.frame_search.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_search.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_search.setObjectName("frame_search")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_search)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox = QtWidgets.QCheckBox(self.frame_search)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_2.addWidget(self.checkBox, 0, 0, 1, 1)
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(self.frame_search)
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.gridLayout_2.addWidget(self.dateTimeEdit_2, 0, 1, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.frame_search)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_2.addWidget(self.checkBox_4, 0, 2, 1, 1)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.frame_search)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout_2.addWidget(self.lineEdit_14, 0, 3, 1, 1)
        self.checkBox_7 = QtWidgets.QCheckBox(self.frame_search)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout_2.addWidget(self.checkBox_7, 0, 4, 1, 1)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.frame_search)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout_2.addWidget(self.lineEdit_15, 0, 5, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame_search)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_2.addWidget(self.checkBox_2, 1, 0, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame_search)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_2.addWidget(self.lineEdit_9, 1, 1, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.frame_search)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout_2.addWidget(self.checkBox_5, 1, 2, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.frame_search)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_2.addWidget(self.lineEdit_12, 1, 3, 1, 1)
        self.checkBox_8 = QtWidgets.QCheckBox(self.frame_search)
        self.checkBox_8.setObjectName("checkBox_8")
        self.gridLayout_2.addWidget(self.checkBox_8, 1, 4, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.frame_search)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_2.addWidget(self.lineEdit_10, 1, 5, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame_search)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_2.addWidget(self.checkBox_3, 2, 0, 1, 1)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.frame_search)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout_2.addWidget(self.lineEdit_13, 2, 1, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.frame_search)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout_2.addWidget(self.checkBox_6, 2, 2, 1, 1)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.frame_search)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout_2.addWidget(self.lineEdit_16, 2, 3, 1, 1)
        self.checkBox_9 = QtWidgets.QCheckBox(self.frame_search)
        self.checkBox_9.setObjectName("checkBox_9")
        self.gridLayout_2.addWidget(self.checkBox_9, 2, 4, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame_search)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_2.addWidget(self.lineEdit_11, 2, 5, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btn_search = QtWidgets.QPushButton(self.frame_search)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/Actions-edit-find-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_search.setIcon(icon)
        self.btn_search.setIconSize(QtCore.QSize(24, 24))
        self.btn_search.setObjectName("btn_search")
        self.horizontalLayout_2.addWidget(self.btn_search)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 3, 0, 1, 6)
        self.gridLayout_9.addWidget(self.frame_search, 0, 0, 1, 1)
        self.frame_edit = QtWidgets.QFrame(self.centralwidget)
        self.frame_edit.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_edit.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_edit.setObjectName("frame_edit")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_edit)
        self.gridLayout_11.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.groupBox = QtWidgets.QGroupBox(self.frame_edit)
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.groupBox)
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        self.gridLayout.addWidget(self.dateTimeEdit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_5.addWidget(self.lineEdit_2, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 1, 0, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_5.addWidget(self.lineEdit_3, 1, 1, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_5, 0, 1, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout_7.addWidget(self.label_4, 0, 0, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_7.addWidget(self.lineEdit_4, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout_7.addWidget(self.label_9, 1, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout_7.addWidget(self.comboBox, 1, 1, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 2, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_edit)
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 0, 0, 1, 1)
        self.toolButton = QtWidgets.QToolButton(self.groupBox_2)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/Actions-list-add-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton.setIcon(icon1)
        self.toolButton.setAutoRaise(True)
        self.toolButton.setObjectName("toolButton")
        self.gridLayout_3.addWidget(self.toolButton, 0, 1, 1, 1)
        self.toolButton_2 = QtWidgets.QToolButton(self.groupBox_2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/Actions-list-remove-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toolButton_2.setIcon(icon2)
        self.toolButton_2.setAutoRaise(True)
        self.toolButton_2.setObjectName("toolButton_2")
        self.gridLayout_3.addWidget(self.toolButton_2, 0, 2, 1, 1)
        self.listView = QtWidgets.QListView(self.groupBox_2)
        self.listView.setObjectName("listView")
        self.gridLayout_3.addWidget(self.listView, 1, 0, 1, 3)
        self.gridLayout_10.addLayout(self.gridLayout_3, 0, 0, 2, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 0, 0, 1, 1)
        self.toolButton_3 = QtWidgets.QToolButton(self.groupBox_2)
        self.toolButton_3.setIcon(icon1)
        self.toolButton_3.setAutoRaise(True)
        self.toolButton_3.setObjectName("toolButton_3")
        self.gridLayout_4.addWidget(self.toolButton_3, 0, 1, 1, 1)
        self.toolButton_4 = QtWidgets.QToolButton(self.groupBox_2)
        self.toolButton_4.setIcon(icon2)
        self.toolButton_4.setAutoRaise(True)
        self.toolButton_4.setObjectName("toolButton_4")
        self.gridLayout_4.addWidget(self.toolButton_4, 0, 2, 1, 1)
        self.listView_3 = QtWidgets.QListView(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView_3.sizePolicy().hasHeightForWidth())
        self.listView_3.setSizePolicy(sizePolicy)
        self.listView_3.setObjectName("listView_3")
        self.gridLayout_4.addWidget(self.listView_3, 1, 0, 1, 3)
        self.gridLayout_10.addLayout(self.gridLayout_4, 0, 1, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_6.addWidget(self.label_10, 0, 0, 1, 1)
        self.toolButton_5 = QtWidgets.QToolButton(self.groupBox_2)
        self.toolButton_5.setIcon(icon1)
        self.toolButton_5.setAutoRaise(True)
        self.toolButton_5.setObjectName("toolButton_5")
        self.gridLayout_6.addWidget(self.toolButton_5, 0, 1, 1, 1)
        self.toolButton_6 = QtWidgets.QToolButton(self.groupBox_2)
        self.toolButton_6.setIcon(icon2)
        self.toolButton_6.setAutoRaise(True)
        self.toolButton_6.setObjectName("toolButton_6")
        self.gridLayout_6.addWidget(self.toolButton_6, 0, 2, 1, 1)
        self.listView_2 = QtWidgets.QListView(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView_2.sizePolicy().hasHeightForWidth())
        self.listView_2.setSizePolicy(sizePolicy)
        self.listView_2.setObjectName("listView_2")
        self.gridLayout_6.addWidget(self.listView_2, 1, 0, 1, 3)
        self.gridLayout_10.addLayout(self.gridLayout_6, 0, 2, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_3.addWidget(self.textEdit)
        self.gridLayout_10.addLayout(self.verticalLayout_3, 1, 1, 1, 2)
        self.gridLayout_11.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btn_edit_confirm = QtWidgets.QPushButton(self.frame_edit)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/Actions-dialog-ok-apply-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_edit_confirm.setIcon(icon3)
        self.btn_edit_confirm.setIconSize(QtCore.QSize(24, 24))
        self.btn_edit_confirm.setObjectName("btn_edit_confirm")
        self.horizontalLayout.addWidget(self.btn_edit_confirm)
        self.btn_edit_cancel = QtWidgets.QPushButton(self.frame_edit)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/Actions-dialog-close-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_edit_cancel.setIcon(icon4)
        self.btn_edit_cancel.setIconSize(QtCore.QSize(24, 24))
        self.btn_edit_cancel.setObjectName("btn_edit_cancel")
        self.horizontalLayout.addWidget(self.btn_edit_cancel)
        self.gridLayout_11.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        self.gridLayout_9.addWidget(self.frame_edit, 1, 0, 1, 1)
        self.tableView = QtWidgets.QTableView(self.centralwidget)
        self.tableView.setObjectName("tableView")
        self.gridLayout_9.addWidget(self.tableView, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuArchiv = QtWidgets.QMenu(self.menubar)
        self.menuArchiv.setObjectName("menuArchiv")
        self.menuZaznam = QtWidgets.QMenu(self.menubar)
        self.menuZaznam.setObjectName("menuZaznam")
        self.menuPomocnik = QtWidgets.QMenu(self.menubar)
        self.menuPomocnik.setObjectName("menuPomocnik")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar_2 = QtWidgets.QToolBar(MainWindow)
        self.toolBar_2.setObjectName("toolBar_2")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar_2)
        self.actionPridat_zaznam = QtWidgets.QAction(MainWindow)
        self.actionPridat_zaznam.setObjectName("actionPridat_zaznam")
        self.actionUpravit_zaznam = QtWidgets.QAction(MainWindow)
        self.actionUpravit_zaznam.setObjectName("actionUpravit_zaznam")
        self.actionOdstranit_zaznam = QtWidgets.QAction(MainWindow)
        self.actionOdstranit_zaznam.setObjectName("actionOdstranit_zaznam")
        self.actionUkoncit = QtWidgets.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/Actions-application-exit-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUkoncit.setIcon(icon5)
        self.actionUkoncit.setObjectName("actionUkoncit")
        self.actionPridat = QtWidgets.QAction(MainWindow)
        self.actionPridat.setIcon(icon1)
        self.actionPridat.setObjectName("actionPridat")
        self.actionUpravit = QtWidgets.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/Actions-document-edit-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionUpravit.setIcon(icon6)
        self.actionUpravit.setObjectName("actionUpravit")
        self.actionOdstranit = QtWidgets.QAction(MainWindow)
        self.actionOdstranit.setIcon(icon2)
        self.actionOdstranit.setObjectName("actionOdstranit")
        self.actionO_programe = QtWidgets.QAction(MainWindow)
        self.actionO_programe.setObjectName("actionO_programe")
        self.menuArchiv.addAction(self.actionUkoncit)
        self.menuZaznam.addAction(self.actionPridat)
        self.menuZaznam.addAction(self.actionUpravit)
        self.menuZaznam.addAction(self.actionOdstranit)
        self.menuPomocnik.addAction(self.actionO_programe)
        self.menubar.addAction(self.menuArchiv.menuAction())
        self.menubar.addAction(self.menuZaznam.menuAction())
        self.menubar.addAction(self.menuPomocnik.menuAction())
        self.toolBar.addAction(self.actionUkoncit)
        self.toolBar_2.addAction(self.actionPridat)
        self.toolBar_2.addAction(self.actionUpravit)
        self.toolBar_2.addAction(self.actionOdstranit)

        self.retranslateUi(MainWindow)
        self.actionUkoncit.triggered['bool'].connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Archiv"))
        self.checkBox.setText(_translate("MainWindow", "Datum:"))
        self.checkBox_4.setText(_translate("MainWindow", "Festival:"))
        self.checkBox_7.setText(_translate("MainWindow", "Solisti:"))
        self.checkBox_2.setText(_translate("MainWindow", "Místo konání:"))
        self.checkBox_5.setText(_translate("MainWindow", "Skladatel:"))
        self.checkBox_8.setText(_translate("MainWindow", "Dirigent:"))
        self.checkBox_3.setText(_translate("MainWindow", "Typ koncertu:"))
        self.checkBox_6.setText(_translate("MainWindow", "Skladba:"))
        self.checkBox_9.setText(_translate("MainWindow", "Poznámka:"))
        self.btn_search.setText(_translate("MainWindow", "Hledat"))
        self.label.setText(_translate("MainWindow", "Datum:"))
        self.label_2.setText(_translate("MainWindow", "Stát konání:"))
        self.label_3.setText(_translate("MainWindow", "Město konání:"))
        self.label_5.setText(_translate("MainWindow", "Sál:"))
        self.label_4.setText(_translate("MainWindow", "Typ koncertu:"))
        self.label_9.setText(_translate("MainWindow", "Festival:"))
        self.label_6.setText(_translate("MainWindow", "Skladatel, skladba"))
        self.toolButton.setText(_translate("MainWindow", "..."))
        self.toolButton_2.setText(_translate("MainWindow", "..."))
        self.label_7.setText(_translate("MainWindow", "Dirigenti"))
        self.toolButton_3.setText(_translate("MainWindow", "..."))
        self.toolButton_4.setText(_translate("MainWindow", "..."))
        self.label_10.setText(_translate("MainWindow", "Solisti"))
        self.toolButton_5.setText(_translate("MainWindow", "..."))
        self.toolButton_6.setText(_translate("MainWindow", "..."))
        self.label_8.setText(_translate("MainWindow", "Poznámka"))
        self.btn_edit_confirm.setText(_translate("MainWindow", "Přidat"))
        self.btn_edit_cancel.setText(_translate("MainWindow", "Zrušit"))
        self.menuArchiv.setTitle(_translate("MainWindow", "Archiv"))
        self.menuZaznam.setTitle(_translate("MainWindow", "Záznam"))
        self.menuPomocnik.setTitle(_translate("MainWindow", "Pomocník"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.toolBar_2.setWindowTitle(_translate("MainWindow", "toolBar_2"))
        self.actionPridat_zaznam.setText(_translate("MainWindow", "Pridat zaznam"))
        self.actionUpravit_zaznam.setText(_translate("MainWindow", "Upravit zaznam"))
        self.actionOdstranit_zaznam.setText(_translate("MainWindow", "Odstranit zaznam"))
        self.actionUkoncit.setText(_translate("MainWindow", "Ukončit"))
        self.actionPridat.setText(_translate("MainWindow", "Přidat"))
        self.actionUpravit.setText(_translate("MainWindow", "Upravit"))
        self.actionOdstranit.setText(_translate("MainWindow", "Odstranit"))
        self.actionO_programe.setText(_translate("MainWindow", "O programe"))

import resource_rc
